import type { ThemeTemplate } from './types';

export const TEMPLATES: ThemeTemplate[] = [
    {
        id: 'template-2026-clean-appointments',
        name: 'Clean Appointments',
        description: 'Clean and direct booking layout with practical trust-building sections.',
        tokens: {
            primary: '#2563eb',
            secondary: '#e2e8f0',
            accent: '#f59e0b',
            text: '#0f172a',
            background: '#ffffff',
            font: 'Inter, sans-serif',
        },
        layout: {
            header: 'header/v1',
            hero: 'hero/v1',
            about: 'about/v1',
            services: 'services/v1',
            product: 'product/v1',
            team: 'team/v1',
            testimonials: 'testimonials/v1',
            pricing: 'pricing/v1',
            faq: 'faq/v1',
            bookingWidget: 'booking-widget/v1',
            contact: 'contact/v1',
            footer: 'footer/v1',
        },
    },
    {
        id: 'template-2026-neon-grid-lab',
        name: 'Neon Grid Lab',
        description: 'Dark cyber-modern lane tuned for high-contrast booking funnels.',
        tokens: {
            primary: '#6366f1',
            secondary: '#1f2937',
            accent: '#10b981',
            text: '#f8fafc',
            background: '#0b1020',
            font: 'Roboto, sans-serif',
        },
        layout: {
            header: 'header/v2',
            hero: 'hero/v2',
            about: 'about/v2',
            services: 'services/v2',
            product: 'product/v2',
            team: 'team/v2',
            testimonials: 'testimonials/v2',
            pricing: 'pricing/v2',
            faq: 'faq/v2',
            bookingWidget: 'booking-widget/v2',
            contact: 'contact/v2',
            footer: 'footer/v2',
        },
    },
    {
        id: 'template-2026-motion-studio',
        name: 'Motion Studio',
        description: 'Energetic storytelling lane that pairs product and gallery proof blocks.',
        tokens: {
            primary: '#0ea5e9',
            secondary: '#e0f2fe',
            accent: '#22d3ee',
            text: '#0f172a',
            background: '#f8fbff',
            font: 'Outfit, sans-serif',
        },
        layout: {
            header: 'header/v3',
            hero: 'hero/v3',
            about: 'about/v3',
            services: 'services/v3',
            product: 'product/v3',
            gallery: 'gallery/v3',
            testimonials: 'testimonials/v3',
            pricing: 'pricing/v3',
            faq: 'faq/v3',
            bookingWidget: 'booking-widget/v3',
            contact: 'contact/v3',
            footer: 'footer/v3',
        },
    },
    {
        id: 'template-2026-elegant-concierge',
        name: 'Elegant Concierge',
        description: 'Luxury-focused editorial lane with refined gallery and premium booking flow.',
        tokens: {
            primary: '#d4af37',
            secondary: '#fdfbf7',
            accent: '#a8862d',
            text: '#2a2a2a',
            background: '#ffffff',
            font: 'Playfair Display, serif',
        },
        layout: {
            header: 'header/v4',
            hero: 'hero/v4',
            about: 'about/v4',
            gallery: 'gallery/v4',
            services: 'services/v4',
            product: 'product/v4',
            testimonials: 'testimonials/v4',
            pricing: 'pricing/v4',
            faq: 'faq/v4',
            bookingWidget: 'booking-widget/v4',
            contact: 'contact/v4',
            footer: 'footer/v4',
        },
    },
    {
        id: 'template-2026-signal-horizon',
        name: 'Signal Horizon',
        description: 'Dark product-marketing lane with logo trust strip and conversion-first rhythm.',
        tokens: {
            primary: '#22d3ee',
            secondary: '#1e293b',
            accent: '#ef4444',
            text: '#ffffff',
            background: '#0b1121',
            font: 'Outfit, sans-serif',
        },
        layout: {
            header: 'header/v5',
            hero: 'hero/v5',
            logos: 'logos/v5',
            services: 'services/v5',
            product: 'product/v5',
            about: 'about/v5',
            testimonials: 'testimonials/v5',
            pricing: 'pricing/v5',
            faq: 'faq/v5',
            bookingWidget: 'booking-widget/v5',
            contact: 'contact/v5',
            footer: 'footer/v5',
        },
    },
    {
        id: 'template-2026-acquisition-shop',
        name: 'Acquisition Shop',
        description: 'High-intent acquisition lane with bolder contrast, conversion rhythm, and operator-focused messaging.',
        tokens: {
            primary: '#ff6a3d',
            secondary: '#ffe9c9',
            accent: '#1da99b',
            text: '#191d24',
            background: '#f6f1e7',
            font: 'Space Grotesk, sans-serif',
        },
        layout: {
            header: 'header/v6',
            hero: 'hero/v6',
            logos: 'logos/v6',
            product: 'product/v6',
            services: 'services/v6',
            team: 'team/v6',
            testimonials: 'testimonials/v6',
            pricing: 'pricing/v6',
            faq: 'faq/v6',
            bookingWidget: 'booking-widget/v6',
            contact: 'contact/v6',
            footer: 'footer/v6',
        },
    },
    {
        id: 'template-2026-prism-grid-conversion',
        name: 'Prism Grid Conversion',
        description: 'Conversion lane using gallery and team blocks for stronger decision support.',
        tokens: {
            primary: '#f97316',
            secondary: '#1e293b',
            accent: '#38bdf8',
            text: '#ffffff',
            background: '#0f172a',
            font: 'Inter, sans-serif',
        },
        layout: {
            header: 'header/v7',
            hero: 'hero/v7',
            about: 'about/v7',
            gallery: 'gallery/v7',
            services: 'services/v7',
            product: 'product/v7',
            team: 'team/v7',
            testimonials: 'testimonials/v7',
            faq: 'faq/v7',
            bookingWidget: 'booking-widget/v7',
            contact: 'contact/v7',
            footer: 'footer/v7',
        },
    },
    {
        id: 'template-2026-salesforce-pipeline',
        name: 'Salesforce Pipeline',
        description: 'Pipeline-oriented lane with logo validation, pricing depth, and offer clarity.',
        tokens: {
            primary: '#0ea5e9',
            secondary: '#e2e8f0',
            accent: '#16a34a',
            text: '#0f172a',
            background: '#ffffff',
            font: 'Inter, sans-serif',
        },
        layout: {
            header: 'header/v8',
            hero: 'hero/v8',
            logos: 'logos/v8',
            about: 'about/v8',
            services: 'services/v8',
            product: 'product/v8',
            testimonials: 'testimonials/v8',
            pricing: 'pricing/v8',
            faq: 'faq/v8',
            bookingWidget: 'booking-widget/v8',
            contact: 'contact/v8',
            footer: 'footer/v8',
        },
    },
    {
        id: 'template-2026-velocity-vsl',
        name: 'Velocity VSL',
        description: 'Dark VSL lane tuned for fast narrative-to-booking progression.',
        tokens: {
            primary: '#f97316',
            secondary: '#1e293b',
            accent: '#38bdf8',
            text: '#f8fafc',
            background: '#020617',
            font: 'Outfit, sans-serif',
        },
        layout: {
            header: 'header/v9',
            hero: 'hero/v9',
            about: 'about/v9',
            services: 'services/v9',
            product: 'product/v9',
            testimonials: 'testimonials/v9',
            pricing: 'pricing/v9',
            faq: 'faq/v9',
            logos: 'logos/v9',
            bookingWidget: 'booking-widget/v9',
            contact: 'contact/v9',
            footer: 'footer/v9',
        },
    },
    {
        id: 'template-2026-aurora-atelier',
        name: 'Aurora Atelier',
        description: 'Premium atelier lane balancing gallery atmosphere and team credibility.',
        tokens: {
            primary: '#ca8a04',
            secondary: '#f5f5f4',
            accent: '#b91c1c',
            text: '#111827',
            background: '#ffffff',
            font: 'Playfair Display, serif',
        },
        layout: {
            header: 'header/v10',
            hero: 'hero/v10',
            about: 'about/v10',
            gallery: 'gallery/v10',
            services: 'services/v10',
            team: 'team/v10',
            testimonials: 'testimonials/v10',
            product: 'product/v10',
            faq: 'faq/v10',
            bookingWidget: 'booking-widget/v10',
            contact: 'contact/v10',
            footer: 'footer/v10',
        },
    },
    {
        id: 'template-2026-fusion-growth',
        name: 'Fusion Growth',
        description: 'Storefront-style long-form sales page for flagship books, bundles, and founder education offers.',
        tokens: {
            primary: '#1f160f',
            secondary: '#f4ecdf',
            accent: '#9a592b',
            text: '#1f160f',
            background: '#f7f1e7',
            font: 'Roboto, sans-serif',
        },
        layout: {
            header: 'header/v13',
            hero: 'hero/v13',
            testimonials: 'testimonials/v13',
            about: 'about/v13',
            logos: 'logos/v13',
            product: 'product/v13',
            services: 'services/v13',
            team: 'team/v13',
            footer: 'footer/v13',
        },
    },
    {
        id: 'template-2026-editorial-pulse',
        name: 'Train of Thought',
        description: 'Editorial blog system with clean storytelling layout for home, listing, and post detail pages.',
        tokens: {
            primary: '#111111',
            secondary: '#e8e4da',
            accent: '#6a675f',
            text: '#181818',
            background: '#f7f6f3',
            font: '"Libre Baskerville", serif',
        },
        layout: {
            header: 'header/v15',
            hero: 'hero/v15',
            blog: 'blog/v15',
            about: 'about/v15',
            contact: 'contact/v15',
            footer: 'footer/v15',
        },
    },
    {
        id: 'template-2026-harmozi-vsl',
        name: 'Harmozi VSL',
        description: 'Storefront-style VSL lane rebuilt from the Acquisition shop long-form book sales page.',
        tokens: {
            primary: '#6f39f6',
            secondary: '#f4f4f4',
            accent: '#ff8d3b',
            text: '#151515',
            background: '#f7f5f1',
            font: 'Poppins, sans-serif',
        },
        layout: {
            header: 'header/v14',
            hero: 'hero/v14',
            testimonials: 'testimonials/v14',
            about: 'about/v14',
            product: 'product/v14',
            services: 'services/v14',
            team: 'team/v14',
            contact: 'contact/v14',
            footer: 'footer/v14',
        },
    },
    {
        id: 'template-2026-spectrum-prime',
        name: 'Spectrum Prime',
        description: 'Balanced all-purpose lane with logos, pricing, and a conversion-safe section flow.',
        tokens: {
            primary: '#2563eb',
            secondary: '#e2e8f0',
            accent: '#ea580c',
            text: '#0f172a',
            background: '#f8fafc',
            font: 'Inter, sans-serif',
        },
        layout: {
            header: 'header/v12',
            hero: 'hero/v12',
            about: 'about/v12',
            services: 'services/v12',
            product: 'product/v12',
            logos: 'logos/v12',
            testimonials: 'testimonials/v12',
            pricing: 'pricing/v12',
            faq: 'faq/v12',
            bookingWidget: 'booking-widget/v12',
            contact: 'contact/v12',
            footer: 'footer/v12',
        },
    },
];
